var express = require("express");
const fileUpload = require("express-fileupload");
var app = express();
var extraction = require("./extraction.js");
//var extraction = require("./teiExtraction.js");
var test = require("./testfile.js");
const multer = require("multer");
var Busboy = require("busboy");
var fs = require("fs");
var http = require("http");
const bodyParser = require("body-parser");
var pathModule = require("path");
const cors = require("cors");
const xml = require("xml");
//import Router from "express-promise-router";
const asyncHandler = require("express-async-handler");

// storage setting for file // file,
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    //console.log("in disk storage", req, file);
    cb(null, "uploads");
  },
  filename: (req, file, cb) => {
    //console.log("in file name", req, file);
    //cb(null, Date.now() + "-" + file.originalname); // 파일 원본이름 저장
    cb(null, "input_file.pdf");
  },
});

app.listen(5000);
app.use(express.static(__dirname));
app.use(cors());
//app.use(router);
//app.use(fileUpload());
//app.use(multer({ dest: __dirname + "/uploads/" }).any());
app.use(multer({ storage: storage }).any());

// respond with "hello world" when a GET request is made to the homepage
app.get("/", function (req, res) {
  var a = test.test();
  //console.log(req.files);
  res.send("hello world");
});

app
  .get("/api", function (req, res) {
    console.log("test for api url");
    res.send("api test success!");
  })
  .post("/api", (req, res, next) => {
    console.log("req.files", req.files);
    res.send("file uploaded successfully from node server");
  });

app.get("/api/process", function (req, res, next) {
  // get_by_pdf
  // qdoc = process_file
  // return qdoc.to_json()
  console.log(" api process ");
  //res.json({});
  res.json({
    concepts: [
      "cad3",
      "vaccine candidates",
      "vaccines",
      "effective ebola vaccines",
      "cad3 vaccine",
      "vaccine efficacy",
      "canada",
      "data",
      "robust data",
      "ebola",
      "ebola virus disease",
      "ebola epidemic",
      "ebola treatment facilities",
      "vac cine",
      "ebola vac cine",
      "ge neva meeting",
      "geneva",
      "meeting",
      "phase",
      "possible",
      "pro vide data",
      "public health",
      "public health agency",
      "public health officials",
      "world health organization",
      "rvsv",
      "studies",
      "tri als",
      "trials",
      "united",
      "west",
    ],
  });
});

// select concept left panel
app.post("/api/cluster", function (req, res, next) {
  console.log(" api cluster post ");
  //res.json({});
  res.json({
    cad3: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["exposed", "expose", 4],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
    ],
    "vaccine candidates": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["capacity", "capacity", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["feasibility", "feasibility", 2],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["open", "open", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["randomized", "randomize", 3],
      ["regulatory", "regulatory", 1],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    vaccines: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["open", "open", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["randomized", "randomize", 3],
      ["regulatory", "regulatory", 1],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    "effective ebola vaccines": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["improve", "improve", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["open", "open", 1],
      ["outbreak", "outbreak", 2],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["quarter", "quarter", 1],
      ["randomized", "randomize", 3],
      ["regulatory", "regulatory", 1],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["stemming", "stem", 1],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    "cad3 vaccine": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["open", "open", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["randomized", "randomize", 3],
      ["regulatory", "regulatory", 1],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    "vaccine efficacy": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["agreement", "agreement", 1],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["feasibility", "feasibility", 2],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["open", "open", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["randomized", "randomize", 3],
      ["regulatory", "regulatory", 1],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    canada: [],
    data: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
    ],
    "robust data": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["data", "datum", 4],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fear", "fear", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["improve", "improve", 1],
      ["industry", "industry", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    ebola: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["family", "family", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["outbreak", "outbreak", 2],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["quarter", "quarter", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "ebola virus disease": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["agreement", "agreement", 1],
      ["available", "available", 2],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["earliest", "early", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["infectious", "infectious", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["outbreak", "outbreak", 2],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["quarter", "quarter", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["resistance", "resistance", 1],
      ["rvsv", "rvsv", 4],
      ["safety", "safety", 2],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    "ebola epidemic": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["family", "family", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["outbreak", "outbreak", 2],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["quarter", "quarter", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "ebola treatment facilities": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["agreement", "agreement", 1],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["earliest", "early", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["likely", "likely", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["outbreak", "outbreak", 2],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quarter", "quarter", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "vac cine": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["open", "open", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["randomized", "randomize", 3],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    "ebola vac cine": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["current", "current", 2],
      ["data", "datum", 4],
      ["demic", "demic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["label", "label", 1],
      ["length", "length", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["open", "open", 1],
      ["outbreak", "outbreak", 2],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["quarter", "quarter", 1],
      ["randomized", "randomize", 3],
      ["reliable", "reliable", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trial", "trial", 3],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    "ge neva meeting": [
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    geneva: [],
    meeting: [
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    phase: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["effective", "effective", 3],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    possible: [
      ["adequate", "adequate", 1],
      ["agreement", "agreement", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quarter", "quarter", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "pro vide data": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["agreement", "agreement", 1],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["members", "member", 1],
      ["newlink", "newlink", 1],
      ["officials", "official", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["quarter", "quarter", 1],
      ["randomized", "randomize", 3],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["resistance", "resistance", 1],
      ["rvsv", "rvsv", 4],
      ["safety", "safety", 2],
      ["scientists", "scientist", 1],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    "public health": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["safety", "safety", 2],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "public health agency": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["safety", "safety", 2],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "public health officials": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clini", "clini", 1],
      ["clinics", "clinic", 1],
      ["communities", "community", 2],
      ["coordinated", "coordinate", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["effort", "effort", 1],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["feasibility", "feasibility", 2],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["safety", "safety", 2],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    "world health organization": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["earliest", "early", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["feasibility", "feasibility", 2],
      ["fluids", "fluid", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["safety", "safety", 2],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
      ["zebov", "zebov", 1],
    ],
    rvsv: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["zebov", "zebov", 1],
    ],
    studies: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["effective", "effective", 3],
      ["exposed", "expose", 4],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["improve", "improve", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["substan", "substan", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    "tri als": [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["communities", "community", 2],
      ["effective", "effective", 3],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["feasibility", "feasibility", 2],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["meeting", "meeting", 3],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["work", "work", 1],
    ],
    trials: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["communities", "community", 2],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["effective", "effective", 3],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["feasibility", "feasibility", 2],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["hospi", "hospi", 1],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["meeting", "meeting", 3],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["populations", "population", 5],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["succeed", "succeed", 1],
      ["tals", "tal", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["vaccines", "vaccine", 5],
      ["work", "work", 1],
    ],
    united: [
      ["bodies", "body", 1],
      ["body", "body", 1],
      ["care", "care", 3],
      ["clinics", "clinic", 1],
      ["controlled", "control", 3],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["diseases", "disease", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["feasibility", "feasibility", 2],
      ["fluids", "fluid", 1],
      ["gathered", "gather", 1],
      ["health", "health", 2],
      ["length", "length", 1],
      ["members", "member", 1],
      ["officials", "official", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["rvsv", "rvsv", 4],
      ["studies", "study", 7],
      ["substan", "substan", 1],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["volunteers", "volunteer", 1],
      ["work", "work", 1],
    ],
    west: [
      ["adequate", "adequate", 1],
      ["affected", "affect", 3],
      ["body", "body", 1],
      ["cad3", "cad3", 1],
      ["care", "care", 3],
      ["designed", "design", 2],
      ["discussed", "discuss", 1],
      ["ebov", "ebov", 1],
      ["effective", "effective", 3],
      ["ers", "er", 1],
      ["exposed", "expose", 4],
      ["family", "family", 1],
      ["fluids", "fluid", 1],
      ["health", "health", 2],
      ["industry", "industry", 1],
      ["infectious", "infectious", 1],
      ["members", "member", 1],
      ["patients", "patient", 2],
      ["phase", "phase", 12],
      ["public", "public", 2],
      ["quantity", "quantity", 1],
      ["regulatory", "regulatory", 1],
      ["representatives", "representative", 1],
      ["rvsv", "rvsv", 4],
      ["tals", "tal", 1],
      ["tial", "tial", 1],
      ["trials", "trial", 9],
      ["vaccine", "vaccine", 8],
      ["zebov", "zebov", 1],
    ],
  });
});

app
  .get(
    "/api/tei",
    asyncHandler(async (req, res) => {
      console.log(" api tei get ");
      try {
        let xmlData = `<?xml version="1.0" encoding="UTF-8"?>`;
        try {
          let data = await extraction.run();
          console.log("data extraction success", data.slice(0, 32));
          xmlData = data;
        } catch (e) {
          console.log("data extraction error", e);
        }
        res.header("Content-Type", "application/xml");
        //xmlData += "<document></section></document>";
        res.status(200).send(xmlData);
      } catch (error) {
        console.log("catching error in async", error);
      }
    })
  )
  .post("/api/tei", (req, res, next) => {
    console.log(" api tei post working ");
    consolew.log("req.files in api tei", req.files);
    res.send("file uploaded api tei");
  });
